(&yes)-> debounce = ({
	typeof((&yes)-> debounce + PORTReadBits((&((&yes)->pin))->ltr,(&((&yes)->pin))->num) ? 1 : -1)
		__val =
		(&yes)-> debounce + PORTReadBits((&((&yes)->pin))->ltr,(&((&yes)->pin))->num) ? 1 : -1;
	typeof(0) __min = 0;
	typeof( ((( (( typeof((&yes)->debounce) )~ (( typeof((&yes)->debounce) )-1 < 1? (-1 - ( (( typeof((&yes)->debounce) )1 << (sizeof(typeof((&yes)->debounce))*8-2)) - 1 + (( typeof((&yes)->debounce) )1 << (sizeof(typeof((&yes)->debounce))*8-2)) ) ) :( typeof((&yes)->debounce) )0) ) ) < ((&yes)->debounce_max)) ? ( (( typeof((&yes)->debounce) )~ (( typeof((&yes)->debounce) )-1 < 1? (-1 - ( (( typeof((&yes)->debounce) )1 << (sizeof(typeof((&yes)->debounce))*8-2)) - 1 + (( typeof ( ( & yes ) -> debounce ) )1 << (sizeof( typeof ( ( & yes ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & yes ) -> debounce ) )0) ) ) : ( ( & yes ) -> debounce_max )) )
		__max =
		( ((( (( typeof((&yes)->debounce) )~ (( typeof((&yes)->debounce) )-1 < 1? (-1 - ( (( typeof((&yes)->debounce) )1 << (sizeof(typeof((&yes)->debounce))*8-2)) - 1 + (( typeof((&yes)->debounce) )1 << (sizeof(typeof((&yes)->debounce))*8-2)) ) ) :( typeof((&yes)->debounce) )0) ) ) < ((&yes)->debounce_max)) ? ( (( typeof((&yes)->debounce) )~ (( typeof((&yes)->debounce) )-1 < 1? (-1 - ( (( typeof((&yes)->debounce) )1 << (sizeof(typeof((&yes)->debounce))*8-2)) - 1 + (( typeof ( ( & yes ) -> debounce ) )1 << (sizeof( typeof ( ( & yes ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & yes ) -> debounce ) )0) ) ) : ( ( & yes ) -> debounce_max )) );
	(void) (&__val == &__min);
	(void) (&__val == &__max);
	__val = __val < __min ? __min: __val;
	__val > __max ? __max: __val;
});

( & no )->debounce = ({
	typeof( ( & no ) -> debounce + PORTReadBits(( & ( ( & no ) -> pin ) )->ltr, ( & ( ( & no ) -> pin ) )->num) ? 1 : - 1 ) __val = ( ( & no ) -> debounce + PORTReadBits(( & ( ( & no ) -> pin ) )->ltr, ( & ( ( & no ) -> pin ) )->num) ? 1 : - 1 );
	typeof( 0 ) __min = ( 0 );
	typeof( ((( (( typeof ( ( & no ) -> debounce ) )~ (( typeof ( ( & no ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & no ) -> debounce ) )0) ) ) < ( ( & no ) -> debounce_max )) ? ( (( typeof ( ( & no ) -> debounce ) )~ (( typeof ( ( & no ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & no ) -> debounce ) )0) ) ) : ( ( & no ) -> debounce_max )) ) __max = ( ((( (( typeof ( ( & no ) -> debounce ) )~ (( typeof ( ( & no ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & no ) -> debounce ) )0) ) ) < ( ( & no ) -> debounce_max )) ? ( (( typeof ( ( & no ) -> debounce ) )~ (( typeof ( ( & no ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & no ) -> debounce ) )1 << (sizeof( typeof ( ( & no ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & no ) -> debounce ) )0) ) ) : ( ( & no ) -> debounce_max )) ); (void) (&__val == &__min); (void) (&__val == &__max); __val = __val < __min ? __min: __val; __val > __max ? __max: __val; }) ;

( & maybe )->debounce = ({
	typeof( ( & maybe ) -> debounce + PORTReadBits(( & ( ( & maybe ) -> pin ) )->ltr, ( & ( ( & maybe ) -> pin ) )->num) ? 1 : - 1 ) __val = ( ( & maybe ) -> debounce + PORTReadBits(( & ( ( & maybe ) -> pin ) )->ltr, ( & ( ( & maybe ) -> pin ) )->num) ? 1 : - 1 );
	typeof( 0 ) __min = ( 0 );
	typeof( ((( (( typeof ( ( & maybe ) -> debounce ) )~ (( typeof ( ( & maybe ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & maybe ) -> debounce ) )0) ) ) < ( ( & maybe ) -> debounce_max )) ? ( (( typeof ( ( & maybe ) -> debounce ) )~ (( typeof ( ( & maybe ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & maybe ) -> debounce ) )0) ) ) : ( ( & maybe ) -> debounce_max )) ) __max = ( ((( (( typeof ( ( & maybe ) -> debounce ) )~ (( typeof ( ( & maybe ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & maybe ) -> debounce ) )0) ) ) < ( ( & maybe ) -> debounce_max )) ? ( (( typeof ( ( & maybe ) -> debounce ) )~ (( typeof ( ( & maybe ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & maybe ) -> debounce ) )1 << (sizeof( typeof ( ( & maybe ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & maybe ) -> debounce ) )0) ) ) : ( ( & maybe ) -> debounce_max )) ); (void) (&__val == &__min); (void) (&__val == &__max); __val = __val < __min ? __min: __val; __val > __max ? __max: __val; }) ;

( & cruise_en )->debounce = ({
	typeof( ( & cruise_en ) -> debounce + PORTReadBits(( & ( ( & cruise_en ) -> pin ) )->ltr, ( & ( ( & cruise_en ) -> pin ) )->num) ? 1 : - 1 ) __val = ( ( & cruise_en ) -> debounce + PORTReadBits(( & ( ( & cruise_en ) -> pin ) )->ltr, ( & ( ( & cruise_en ) -> pin ) )->num) ? 1 : - 1 );
	typeof( 0 ) __min = ( 0 );
	typeof( ((( (( typeof ( ( & cruise_en ) -> debounce ) )~ (( typeof ( ( & cruise_en ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_en ) -> debounce ) )0) ) ) < ( ( & cruise_en ) -> debounce_max )) ? ( (( typeof ( ( & cruise_en ) -> debounce ) )~ (( typeof ( ( & cruise_en ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_en ) -> debounce ) )0) ) ) : ( ( & cruise_en ) -> debounce_max )) ) __max = ( ((( (( typeof ( ( & cruise_en ) -> debounce ) )~ (( typeof ( ( & cruise_en ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_en ) -> debounce ) )0) ) ) < ( ( & cruise_en ) -> debounce_max )) ? ( (( typeof ( ( & cruise_en ) -> debounce ) )~ (( typeof ( ( & cruise_en ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_en ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_en ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_en ) -> debounce ) )0) ) ) : ( ( & cruise_en ) -> debounce_max )) ); (void) (&__val == &__min); (void) (&__val == &__max); __val = __val < __min ? __min: __val; __val > __max ? __max: __val; }) ;

( & cruise_mode )->debounce = ({
	typeof( ( & cruise_mode ) -> debounce + PORTReadBits(( & ( ( & cruise_mode ) -> pin ) )->ltr, ( & ( ( & cruise_mode ) -> pin ) )->num) ? 1 : - 1 ) __val = ( ( & cruise_mode ) -> debounce + PORTReadBits(( & ( ( & cruise_mode ) -> pin ) )->ltr, ( & ( ( & cruise_mode ) -> pin ) )->num) ? 1 : - 1 );
	typeof( 0 ) __min = ( 0 );
	typeof( ((( (( typeof ( ( & cruise_mode ) -> debounce ) )~ (( typeof ( ( & cruise_mode ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_mode ) -> debounce ) )0) ) ) < ( ( & cruise_mode ) -> debounce_max )) ? ( (( typeof ( ( & cruise_mode ) -> debounce ) )~ (( typeof ( ( & cruise_mode ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_mode ) -> debounce ) )0) ) ) : ( ( & cruise_mode ) -> debounce_max )) ) __max = ( ((( (( typeof ( ( & cruise_mode ) -> debounce ) )~ (( typeof ( ( & cruise_mode ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_mode ) -> debounce ) )0) ) ) < ( ( & cruise_mode ) -> debounce_max )) ? ( (( typeof ( ( & cruise_mode ) -> debounce ) )~ (( typeof ( ( & cruise_mode ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_mode ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_mode ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_mode ) -> debounce ) )0) ) ) : ( ( & cruise_mode ) -> debounce_max )) ); (void) (&__val == &__min); (void) (&__val == &__max); __val = __val < __min ? __min: __val; __val > __max ? __max: __val; }) ;

( & cruise_up )->debounce = ({
	typeof( ( & cruise_up ) -> debounce + PORTReadBits(( & ( ( & cruise_up ) -> pin ) )->ltr, ( & ( ( & cruise_up ) -> pin ) )->num) ? 1 : - 1 ) __val = ( ( & cruise_up ) -> debounce + PORTReadBits(( & ( ( & cruise_up ) -> pin ) )->ltr, ( & ( ( & cruise_up ) -> pin ) )->num) ? 1 : - 1 );
	typeof( 0 ) __min = ( 0 );
	typeof( ((( (( typeof ( ( & cruise_up ) -> debounce ) )~ (( typeof ( ( & cruise_up ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_up ) -> debounce ) )0) ) ) < ( ( & cruise_up ) -> debounce_max )) ? ( (( typeof ( ( & cruise_up ) -> debounce ) )~ (( typeof ( ( & cruise_up ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_up ) -> debounce ) )0) ) ) : ( ( & cruise_up ) -> debounce_max )) ) __max = ( ((( (( typeof ( ( & cruise_up ) -> debounce ) )~ (( typeof ( ( & cruise_up ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_up ) -> debounce ) )0) ) ) < ( ( & cruise_up ) -> debounce_max )) ? ( (( typeof ( ( & cruise_up ) -> debounce ) )~ (( typeof ( ( & cruise_up ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_up ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_up ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_up ) -> debounce ) )0) ) ) : ( ( & cruise_up ) -> debounce_max )) ); (void) (&__val == &__min); (void) (&__val == &__max); __val = __val < __min ? __min: __val; __val > __max ? __max: __val; }) ;

( & cruise_down )->debounce = ({
	typeof( ( & cruise_down ) -> debounce + PORTReadBits(( & ( ( & cruise_down ) -> pin ) )->ltr, ( & ( ( & cruise_down ) -> pin ) )->num) ? 1 : - 1 ) __val = ( ( & cruise_down ) -> debounce + PORTReadBits(( & ( ( & cruise_down ) -> pin ) )->ltr, ( & ( ( & cruise_down ) -> pin ) )->num) ? 1 : - 1 );
	typeof( 0 ) __min = ( 0 );
	typeof( ((( (( typeof ( ( & cruise_down ) -> debounce ) )~ (( typeof ( ( & cruise_down ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_down ) -> debounce ) )0) ) ) < ( ( & cruise_down ) -> debounce_max )) ? ( (( typeof ( ( & cruise_down ) -> debounce ) )~ (( typeof ( ( & cruise_down ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_down ) -> debounce ) )0) ) ) : ( ( & cruise_down ) -> debounce_max )) ) __max = ( ((( (( typeof ( ( & cruise_down ) -> debounce ) )~ (( typeof ( ( & cruise_down ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_down ) -> debounce ) )0) ) ) < ( ( & cruise_down ) -> debounce_max )) ? ( (( typeof ( ( & cruise_down ) -> debounce ) )~ (( typeof ( ( & cruise_down ) -> debounce ) )-1 < 1? (-1 - ( (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) - 1 + (( typeof ( ( & cruise_down ) -> debounce ) )1 << (sizeof( typeof ( ( & cruise_down ) -> debounce ) )*8-2)) ) ) :( typeof ( ( & cruise_down ) -> debounce ) )0) ) ) : ( ( & cruise_down ) -> debounce_max )) ); (void) (&__val == &__min); (void) (&__val == &__max); __val = __val < __min ? __min: __val; __val > __max ? __max: __val; }) ;    }
